<a href="https://colab.research.google.com/github/mohitgupta82345-sys/DSA-practice/blob/main/pandas_Assiginment02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [ ]:
## 1. Create a DataFrame named student_df from a dictionary containing the columns Name, Age, and City for
## four students.

data = {
    'Name': ['Mohit', 'Rahul', 'Aman', 'Karan'],
    'Age': [20, 21, 19, 22],
    'City': ['Mathura', 'Delhi', 'Agra', 'Jaipur']
}

student_df = pd.DataFrame(data)

    Name  Age     City
0  Mohit   20  Mathura
1  Rahul   21    Delhi
2   Aman   19     Agra
3  Karan   22   Jaipur

In [ ]:
## 2. Display the complete student_df DataFrame.
student_df

    Name  Age     City
0  Mohit   20  Mathura
1  Rahul   21    Delhi
2   Aman   19     Agra
3  Karan   22   Jaipur

In [ ]:
## 3. Write code to display the column names of student_df.
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [ ]:
## 4. Retrieve the Name column from student_df.
student_df['Name']

0    Mohit
1    Rahul
2     Aman
3    Karan
Name: Name, dtype: object

In [ ]:
## 5. Retrieve the City column from student_df using square-bracket notation.
student_df['City']

0    Mathura
1      Delhi
2       Agra
3     Jaipur
Name: City, dtype: object

In [ ]:
## 6. Create a new DataFrame from student_df containing only the columns Name and City.
new_df = student_df[['Name', 'City']]

In [ ]:
## 7. Create a DataFrame named book_df from a dictionary of equal-length lists containing Book, Author, and
## Price.

In [ ]:
 book_df = pd.DataFrame({
    'Book': ['Harry Potter', 'physics', 'maths'],
    'Author': ['J.K. Rowling', 'H.c verma', 'R.D sharma' ],
    'Price': [1099, 899, 799]
})

In [ ]:
book_df

           Book        Author  Price
0  Harry Potter  J.K. Rowling   1099
1       physics     H.c verma    899
2         maths    R.D sharma    799

In [ ]:
## 8. Add a new column named Publisher to book_df and assign the same publisher name to every row.
book_df['Publisher'] = 'XYZ'
book_df

           Book        Author  Price Publisher
0  Harry Potter  J.K. Rowling   1099       XYZ
1       physics     H.c verma    899       XYZ
2         maths    R.D sharma    799       XYZ

In [ ]:
#9. Create a five-row DataFrame and assign the values generated by np.arange(5) to a new column named
#SerialNo.
df = pd.DataFrame ({
    'Name': ['Mohit', 'sahil', 'Anshul', 'mehul', 'rishabh']
})

In [ ]:
df

      Name
0    Mohit
1    sahil
2   Anshul
3    mehul
4  rishabh

In [ ]:
df['SerialNo'] = np.arange(5)

In [ ]:
df

      Name  SerialNo
0    Mohit         0
1    sahil         1
2   Anshul         2
3    mehul         3
4  rishabh         4

In [ ]:
##10. Delete the SerialNo column from the DataFrame created in Question 9.
del df['SerialNo']

In [5]:
## 11. Create a DataFrame named movie_df containing the columns Movie, Year, and Rating.

movie_df = pd.DataFrame({
    "Movie": ["3 Idiots", "Dangal", "KGF"],
    "Year": [2009, 2016, 2018],
    "Rating": [8.4, 8.3, 8.2]
})

In [6]:
movie_df

      Movie  Year  Rating
0  3 Idiots  2009     8.4
1    Dangal  2016     8.3
2       KGF  2018     8.2

In [8]:
## 12. From movie_df, create another DataFrame containing the columns Movie, Rating, and a new requested
## column named Director that is not present in the original DataFrame.
new_df = movie_df[["Movie", "Rating"]].copy()
new_df["Director"] = ["Rajkumar Hirani", "Nitesh Tiwari", "Prashanth Neel"]
new_df

      Movie  Rating         Director
0  3 Idiots     8.4  Rajkumar Hirani
1    Dangal     8.3    Nitesh Tiwari
2       KGF     8.2   Prashanth Neel

In [9]:
## 13. Create a Series containing two city names at indexes 0 and 3.
cities = pd.Series(
    ["Delhi", "Mumbai"],
    index=[0, 3]
)
cities

0     Delhi
3    Mumbai
dtype: object

In [11]:
## 14. Assign the Series from Question 13 to a new column named Branch in a four-row DataFrame.
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"]
})
df["Branch"] = cities
df

  Name  Branch
0    A   Delhi
1    B     NaN
2    C     NaN
3    D  Mumbai

In [12]:
## 15. Copy a small table from a spreadsheet or webpage and write code to read it into a DataFrame named
## copied_df using the clipboard-reading method covered in class.

In [14]:
## 16. Create a five-row DataFrame named employee_df with columns Employee, Department, and
## Experience. Display only Employee and Experience in a new DataFrame.
employee_df = pd.DataFrame({
    "Employee": ["Rahul", "Aman", "Priya", "Neha", "Rohit"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing"],
    "Experience": [2, 4, 3, 5, 1]
})
new_df = employee_df[["Employee", "Experience"]]
new_df

  Employee  Experience
0    Rahul           2
1     Aman           4
2    Priya           3
3     Neha           5
4    Rohit           1

In [15]:
## 17. Using employee_df, retrieve the Department column using one-column access and then display all
## column names.
employee_df["Department"]

0           IT
1           HR
2      Finance
3           IT
4    Marketing
Name: Department, dtype: object

In [16]:
## 18. Add a new column named Office to employee_df and assign 'Head Office' to every row. Then display the
## updated DataFrame.
employee_df["Office"] = "Head Office"
employee_df

  Employee Department  Experience       Office
0    Rahul         IT           2  Head Office
1     Aman         HR           4  Head Office
2    Priya    Finance           3  Head Office
3     Neha         IT           5  Head Office
4    Rohit  Marketing           1  Head Office

In [17]:
##19. Replace the values in the Office column with numbers generated using np.arange(5).
employee_df["Office"] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0    Rahul         IT           2       0
1     Aman         HR           4       1
2    Priya    Finance           3       2
3     Neha         IT           5       3
4    Rohit  Marketing           1       4

In [18]:
## 20. Create a Series named office_names containing 'Delhi', 'Mumbai', and 'Pune' at indexes 0, 2, and 4.
## Assign it to the Office column of employee_df and display the result.
office_names = pd.Series(["Delhi", "Mumbai", "Pune"], index=[0, 2, 4])
employee_df["Office"] = office_names
employee_df

  Employee Department  Experience  Office
0    Rahul         IT           2   Delhi
1     Aman         HR           4     NaN
2    Priya    Finance           3  Mumbai
3     Neha         IT           5     NaN
4    Rohit  Marketing           1    Pune

In [19]:
## 21. Delete the Office column from employee_df and display the remaining columns.
del employee_df["Office"]
employee_df

  Employee Department  Experience
0    Rahul         IT           2
1     Aman         HR           4
2    Priya    Finance           3
3     Neha         IT           5
4    Rohit  Marketing           1

In [21]:
## 22. Create a DataFrame named product_df from a dictionary containing Product, Category, and Price. Then
## construct another DataFrame with the columns ordered as Price, Product, Category.
product_df = pd.DataFrame({
    "Product": ["Laptop", "Tablet", "Phone"],
    "Category": ["Electronics", "Electronics", "Electronics"],
    "Price": [1000, 500, 800]
})
product_df[["Price", "Product", "Category"]]

   Price Product     Category
0   1000  Laptop  Electronics
1    500  Tablet  Electronics
2    800   Phone  Electronics

In [22]:
## 23. Construct a DataFrame from existing data while requesting four columns, where one of the requested
## columns does not exist in the source data. Display the resulting DataFrame and inspect what appears in the
## missing column.
product_df = pd.DataFrame({
    "Product": ["Laptop", "Tablet", "Phone"],
    "Category": ["Electronics", "Electronics", "Electronics"],
    "Price": [1000, 500, 800]
})
product_df[["Price", "Product", "Category", "Quantity"]]

KeyError: "['Quantity'] not in index"