<a href="https://colab.research.google.com/github/mohitgupta82345-sys/DSA-practice/blob/main/PandasSeries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
sales = pd.Series([2,3,5])

In [4]:
sales

0    2
1    3
2    5
dtype: int64

In [5]:
sales[2]

np.int64(5)

In [6]:
sales[0:4]

0    2
1    3
2    5
dtype: int64

In [7]:
sales.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
sales.values

array([2, 3, 5])

In [9]:
sales.dtype

dtype('int64')

In [ ]:
sales.head(2)

0    2
1    3
dtype: int64

In [ ]:
sales.tail(2)

1    3
2    5
dtype: int64

In [ ]:
sales.sort_values()

0    2
1    3
2    5
dtype: int64

In [ ]:
sales1=pd.Series([2,1,5,7,3,6,9,8,10])

In [ ]:
sales1.sort_values()

1     1
0     2
4     3
2     5
5     6
3     7
7     8
6     9
8    10
dtype: int64

In [ ]:
sales1.count()

np.int64(9)

In [ ]:
sales1.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [ ]:
sales1.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
dtype: bool

In [ ]:
sales+1

0    3
1    4
2    6
dtype: int64

In [ ]:
sales*2

0     4
1     6
2    10
dtype: int64

In [ ]:
sales**2

0     4
1     9
2    25
dtype: int64

In [ ]:
sales_missing = pd.Series([2,None,5])

In [ ]:
sales_missing

0    2.0
1    NaN
2    5.0
dtype: float64

In [ ]:
sales_missing.fillna(1)

0    2.0
1    1.0
2    5.0
dtype: float64

In [ ]:
data1 = pd.DataFrame({
    'Name':['Anna','Ben'],'Age':[20,21]
})

In [ ]:
data1

   Name  Age
0  Anna   20
1   Ben   21

In [ ]:
s1 = pd.Series([1,2,3,4,5])

In [ ]:
s2 = pd.Series([10,20,30,40,50])

In [ ]:
data = pd.DataFrame({'C1':s1,'C2':s2})

In [ ]:
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [ ]:
data.shape

(5, 2)

In [ ]:
data.columns

Index(['C1', 'C2'], dtype='object')

In [ ]:
data.dtypes

C1    int64
C2    int64
dtype: object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [ ]:
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

In [ ]:
data1.set_index('Name',inplace=True)

In [ ]:
data1.index

Index(['Anna', 'Ben'], dtype='object', name='Name')

In [ ]:
data1

      Age
Name
Anna   20
Ben    21

In [ ]:
data1.reset_index(inplace=True)

In [ ]:
data1

   Name  Age
0  Anna   20
1   Ben   21

In [ ]:
multi_data = pd.DataFrame({'Park':['A','A','B','B'],'Name':['Anna','Ben','Chris','Daisy'],'Lemonades':[2,3,4,5]}).set_index(['Park','Name'])

In [ ]:
multi_data

            Lemonades
Park Name
A    Anna           2
     Ben            3
B    Chris          4
     Daisy          5

In [ ]:
data1

   Name  Age
0  Anna   20
1   Ben   21

In [ ]:
s1 = pd.Series([data  == 1,2,3,4,5])
s2 = pd.Series([data == 10,20,30,40,50])

In [ ]:
data['Tips']=[1,2,3,4,5]

In [ ]:
data

   C1  C2  Tips
0   1  10     1
1   2  20     2
2   3  30     3
3   4  40     4
4   5  50     5

In [ ]:
data.loc[data['Tips']==5]=6

In [ ]:
data

   C1  C2  Tips
0   1  10     1
1   2  20     2
2   3  30     3
3   4  40     4
4   6   6     6

In [ ]:
data.rename(columns={'Tips':'C3'},inplace=True)

In [ ]:
data

   C1  C2  C3
0   1  10   1
1   2  20   2
2   3  30   3
3   4  40   4
4   6   6   6

In [ ]:
data = data.drop(columns = ['C3'])

In [ ]:
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   6   6

In [ ]:
data.set_index('C1',inplace=True)

In [ ]:
data

    C2
C1
1   10
2   20
3   30
4   40
6    6

In [ ]:
data.loc[2,'C2']

np.int64(20)

In [ ]:
data.reset_index(inplace=True)

In [ ]:
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   6   6

In [ ]:
multi_data=pd.DataFrame({'Park':['A','A','B','B'],'Name':['Anna','Ben','Chris','Daisy'],'Lemonades':[2,3,4,5]}).set_index(['Park','Name'])

In [ ]:
multi_data

            Lemonades
Park Name
A    Anna           2
     Ben            3
B    Chris          4
     Daisy          5

In [ ]:
multi_data.query('Lemonades>3')

            Lemonades
Park Name
B    Chris          4
     Daisy          5

In [ ]:
pd.read_csv('Lemonades_sales.csv')

   Unnamed: 0  C1  C2
0           0   1  10
1           1   2  20
2           2   3  30
3           3   4  40
4           4   6   6

In [ ]:
data.to_csv('Lemonades_sales.csv')

In [ ]:
import numpy as np

In [ ]:
dictt = {'x':[1,2,3,4],'y':np.array([10,20,30,40]),'z':50}
pd.DataFrame(dictt)

   x   y   z
0  1  10  50
1  2  20  50
2  3  30  50
3  4  40  50

In [ ]:
data.drop_duplicates()

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   6   6

In [ ]:
data.replace('R1','C1')

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   6   6

In [ ]:
data['C1']=data['C1'].astype(float)

In [ ]:
data

    C1  C2
0  1.0  10
1  2.0  20
2  3.0  30
3  4.0  40
4  6.0   6

In [ ]:
                                                                          #Assignment

In [ ]:
#1. Create a Pandas Series named sales containing the values 120, 150, 180 and 210.
sales = pd.Series([120,150,180,210])

In [ ]:
#2. For the Series below, write the command that displays only the stored data values.
marks = pd.Series([72, 81, 69, 90])
marks

0    72
1    81
2    69
3    90
dtype: int64

In [ ]:
#3. For the same Series marks, write the command that displays its index.
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
#4. Create a Series of temperatures 28, 31, 30 and 29 using the index labels Mon, Tue, Wed and Thu.
temperatures = pd.Series([28,31,30,29],index=['Mon','Tue','Wed','Thu'])
temperatures

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

In [ ]:
#5. Given the Series below, write the expression to retrieve the population value for Jaipur.
#population = Series([35, 42, 31], index=[&#39;Delhi&#39;,&#39;Mumbai&#39;,&#39;Jaipur&#39;])
population = pd.Series([35,42,31],index=['Delhi','Mumbai','Jaipur'])
population

Delhi     35
Mumbai    42
Jaipur    31
dtype: int64

In [ ]:
#6. Write a Boolean-filtering expression to display only the values greater than 50 from the Series score.
#score = Series([35, 68, 44, 79, 52])
score = pd.Series([35,68,44,79,52])
(score[score>50])

1    68
3    79
4    52
dtype: int64

In [ ]:
#7. Using the Series below, write an expression to check whether the label Chemistry is present in its index.
#subjects = Series([76, 83, 91], index=[&#39;Physics&#39;,&#39;Chemistry&#39;,&#39;Maths&#39;])
subjects = pd.Series([76,83,91],index=['Physics','Chemistry','Maths'])
subjects

Physics      76
Chemistry    83
Maths        91
dtype: int64

In [ ]:
#8. Write the Pandas Series method that converts a Series into a Python dictionary.
series = pd.Series([1,2,3,4,5])
series.to_dict()

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}

In [ ]:
#9. Convert the following dictionary into a Pandas Series named price_series.
#prices = {&#39;Pen&#39;: 10, &#39;Notebook&#39;: 55, &#39;Bag&#39;: 700}
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
price_series = pd.Series(prices)
print(price_series)

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
#10. When a dictionary is converted into a Series without separately specifying an index, what becomes the
#Series index?

In [ ]:
#11. In the following code, identify the label that will have a missing value.
data = {'A':10,'B':20, 'C':30}
s = pd.Series(data, index=['A','B','C','D'])
s

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [ ]:
#12. Write a Pandas expression using isnull to identify missing values in a Series named s.
s.isnull()

A    False
B    False
C    False
D     True
dtype: bool

In [ ]:
#13. Write a Pandas expression using notnull to identify non-missing values in a Series named s.
s.notnull()

A     True
B     True
C     True
D    False
dtype: bool

In [ ]:
#14. Assign the name Monthly Sales to a Series named sales.
sales.name = "Monthly_Sales"

In [ ]:
#15. Assign the name Month to the index of a Series named sales.
sales.index.name = "Month"

In [ ]:
#16. Predict which labelled entries will be returned by the following expression.
s = pd.Series([18,45,27,61],index=["P","Q","R","S"])
s[s>30]

Q    45
S    61
dtype: int64

In [ ]:
#17. Predict the result of each membership test. Remember that membership is checked against the Series index.
s = pd.Series([500,600,700],index=[['East','West','North']])
'West' in s
500 in s

False

In [ ]:
#18.A dictionary contains data for Delhi, Pune and Kochi. Create a Series using the ordered index Delhi, Kochi,
#Pune, Chennai. State which label will receive NaN.
data = {"Delhi": 80,"Pune": 65,"Kochi": 70}
s = pd.Series(data, index=["Delhi", "Kochi", "Pune", "Chennai"])
print(s[s.isna()].index)

Index(['Chennai'], dtype='object')

In [ ]:
#The following Series contains one missing value. State the Boolean output conceptually produced by
#pd.isnull(s) for W, X, Y and Z.
s = pd.Series({'W':10,'X':20,'Y':30},index=['W','X','Y'])
print(pd.isnull(s))

W    False
X    False
Y    False
dtype: bool

In [ ]:
#20.For Question 19, state the Boolean output conceptually produced by pd.notnull(s) for W, X, Y and Z.
print(pd.notnull(s))

W    True
X    True
Y    True
dtype: bool

In [ ]:
#21.Predict the result of adding the following two Series. Show the result for labels A, B and C.
s1 =pd.Series([10,20,30],index=['A','B','C'])
s2 =pd.Series([1,2,3],index=['C','A','B'])
s1+s2

A    12
B    23
C    31
dtype: int64

In [ ]:
#22.Explain why the following addition produces a missing value for some labels even though both Series contain numeric data.
s1 = pd.Series({'A':12,'B':18})
s2 = pd.Series({'B':5,'C':9})
s1+s2

A     NaN
B    23.0
C     NaN
dtype: float64

In [ ]:
#23.Write code to convert the following Series to a dictionary named stock_dict and then reconstruct a new Series named stock2 from that dictionary.
stock = pd.Series([25,40,18],index=['Item 1','Item 2','Item 3'])
stock_dict = stock.to_dict()
stock2 = pd.Series(stock_dict)
print(stock2)

Item 1    25
Item 2    40
Item 3    18
dtype: int64

In [ ]:
#24.Create a Series from the dictionary below using the index order History, English, Science, Maths. Then write an expression to display only values greater than 70.
marks = pd.Series({'History': 72, 'English': 81, 'Science': 69, 'Maths': 9})
marks[marks>70]

History    72
English    81
dtype: int64

In [ ]:
#25. A Series is named Revenue and its index is named Branch. Write the two assignment statements needed to apply these names to a Series object called rev.
rev= pd.Series()
rev.name = "Revenue"
rev.index.name="Branch"
rev

Series([], Name: Revenue, dtype: object)

In [ ]:
#26.Analyse the following program. Determine the final result of total for every label and explain how Pandas index alignment determines each value.
north = pd.Series({'Jan':40,'Feb': 55, 'Mar': 60})
south = pd.Series({'Feb':20,'Mar': 25,'Apr': 30})
total = north + south
total

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

In [ ]:
#27.Study the code and answer all parts: (a) Which label contains NaN? (b) What does pd.isnull(result) return for that label? (c) Why is the missing value created? (d) Which labels retain actual numeric values?
d = {'Red':12,'Blue':18,'Green':24}
labels = ['Red','Yellow','Blue','Green']
result = pd.Series(d,labels)
result

Red       12.0
Yellow     NaN
Blue      18.0
Green     24.0
dtype: float64

In [ ]:
#28. Without running the code, trace the complete transformation and state the index and values of s2. Then state whether s and s2 represent the same labelled data.
s = pd.Series([90,75,82],index = ['Ravi','Aman','Neha'])
d = s.to_dict()
s2 = pd.Series(d)
s2

Ravi    90
Aman    75
Neha    82
dtype: int64

In [ ]:
#29.Write a short Pandas program that creates a labelled Series for four products and sales, displays its valuesand index, selects one label, filters sales above 500, checks whether a label exists, and converts the Series to a dictionary.
products = pd.Series( ["Laptop", "Mobile", "Tablet", "Mouse"],index=["P1", "P2", "P3", "P4"])
sales = pd.Series([1000, 500, 800, 300], index=["P1", "P2", "P3", "P4"])
print(products.values)
print(products.index)
print(sales.values)
print(sales.index)
print(sales[sales>500])
print('P2' in sales)

['Laptop' 'Mobile' 'Tablet' 'Mouse']
Index(['P1', 'P2', 'P3', 'P4'], dtype='object')
[1000  500  800  300]
Index(['P1', 'P2', 'P3', 'P4'], dtype='object')
P1    1000
P3     800
dtype: int64
True

In [ ]:
#30. Analyse the following code and answer all parts: (a) What is the index order of s? (b) Which label containsNaN? (c) What will the Boolean filter s[s &gt; 20] return? (d) What will pd.notnull(s) indicate for each label? (e) What are the Series name and index name after the final two statements?
data = {'A':15,"B":35,'C':25,}
s = pd.Series(data,index=['C','A','D','B'])
s.name = "Observations"
s.index.name = "Category"
print(s.index)
print(s.isna())
print(s[s>20])
print(pd.notnull(s))
print(s.name)
print(s.index.name)

Index(['C', 'A', 'D', 'B'], dtype='object', name='Category')
Category
C    False
A    False
D     True
B    False
Name: Observations, dtype: bool
Category
C    25.0
B    35.0
Name: Observations, dtype: float64
Category
C     True
A     True
D    False
B     True
Name: Observations, dtype: bool
Observations
Category